### ISSUE TITLE
Error with x64

### ISSUE THREAD

**Issue by quanglam2807** [cloudcrypt/SQLite-Universal-WinJS-Component#2]
I followed the instructions but here what I got when I tried to run my app in x64 (it works fine with x86)

```
Error C1083 Cannot open precompiled header file: 'x64\Debug\pch.pch': No such file or directory
```

**Comment by cloudcrypt** [comment]
Thank you, fixed in a48dd0c89565ccf618eab30f84922b047c0b61e7 by changing the Precompiled Header option for the file pch.cpp from "Use (/Yu)" to "Create (/Yc)" for the x64 Debug and Release configurations. Sorry for the delay, recently got back to my main computer. Please let me know if it still doesn't work.
